import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import useSWR from "swr";
import ArtPieces from "@/components/ArtPieces/ArtPieces.js";
import Spotlight from "@/components/Spotlight/Spotlight";

const inter = Inter({ subsets: ["latin"] });

const fetcher = (...args) => fetch(...args).then((res) => res.json());
export default function Home() {
  const { data, error, isLoading } = useSWR(
    "https://example-apis.vercel.app/api/art",
    fetcher
  );

  if (error) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;
  console.log("data", data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-red-300">
        <Spotlight pieces={data} />
        <ArtPieces pieces={data} />
      </main>
    </>
  );
}
